//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VmgPortal.Modules.KPIData.Admin.DotDanhGia {
    
    
    public partial class QuanLyGiaoViec {
        
        /// <summary>
        /// litNav control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litNav;
        
        /// <summary>
        /// litTab0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTab0;
        
        /// <summary>
        /// QuanLyCongViecKPIVaNhanVine1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VmgPortal.Modules.KPIData.Admin.DotDanhGia.QuanLyCongViecKPIVaNhanVine QuanLyCongViecKPIVaNhanVine1;
        
        /// <summary>
        /// litTab1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTab1;
        
        /// <summary>
        /// QuanLyCongViecKTXVaNhanVien1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VmgPortal.Modules.KPIData.Admin.DotDanhGia.QuanLyCongViecKTXVaNhanVien QuanLyCongViecKTXVaNhanVien1;
        
        /// <summary>
        /// litTab2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTab2;
        
        /// <summary>
        /// QuanLyCongViecPSVaNhanVien1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VmgPortal.Modules.KPIData.Admin.DotDanhGia.QuanLyCongViecPSVaNhanVien QuanLyCongViecPSVaNhanVien1;
    }
}
