//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VmgPortal.Modules.KPIData.Admin.HoTroCongViec {
    
    
    public partial class DanhGiaCBCNV {
        
        /// <summary>
        /// tableContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tableContent;
        
        /// <summary>
        /// dropDotDanhGia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropDotDanhGia;
        
        /// <summary>
        /// DanhGiaCBCNV_KhoiLuong1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VmgPortal.Modules.KPIData.Admin.HoTroCongViec.DanhGiaCBCNV_KhoiLuong DanhGiaCBCNV_KhoiLuong1;
        
        /// <summary>
        /// DanhGiaCBCNV_KhoiLuongCVKTX1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VmgPortal.Modules.KPIData.Admin.HoTroCongViec.DanhGiaCBCNV_KhoiLuongCVKTX DanhGiaCBCNV_KhoiLuongCVKTX1;
        
        /// <summary>
        /// DanhGiaCBCNV_KhoiLuongCVPhatSinh1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VmgPortal.Modules.KPIData.Admin.HoTroCongViec.DanhGiaCBCNV_KhoiLuongCVPhatSinh DanhGiaCBCNV_KhoiLuongCVPhatSinh1;
    }
}
