//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move file(s) to Recycle Bin:.
        /// </summary>
        internal static string LOC_ERROR_CANNOTMOVETORECYCLEBIN {
            get {
                return ResourceManager.GetString("LOC_ERROR_CANNOTMOVETORECYCLEBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move file(s) to Recycle Bin: Access denied. Please, check that you have Write permission for the current directory and file..
        /// </summary>
        internal static string LOC_ERROR_CANNOTMOVETORECYCLEBIN_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_CANNOTMOVETORECYCLEBIN_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restore files(s) from Recycle Bin:.
        /// </summary>
        internal static string LOC_ERROR_CANNOTRESTORE {
            get {
                return ResourceManager.GetString("LOC_ERROR_CANNOTRESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restore files(s) from Recycle Bin: Access denied. Please, check that you have Write permission for the current directory and file..
        /// </summary>
        internal static string LOC_ERROR_CANNOTRESTORE_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_CANNOTRESTORE_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot select files from Recycle Bin..
        /// </summary>
        internal static string LOC_ERROR_CANNOTSELECTFILEINRECYCLEBIN {
            get {
                return ResourceManager.GetString("LOC_ERROR_CANNOTSELECTFILEINRECYCLEBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot copy directory &quot;{0}&quot;:.
        /// </summary>
        internal static string LOC_ERROR_COPY_DIRECTORY {
            get {
                return ResourceManager.GetString("LOC_ERROR_COPY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot copy directory &quot;{0}&quot;: Access denied. Please, check that you have Write permission for the current directory and file..
        /// </summary>
        internal static string LOC_ERROR_COPY_DIRECTORY_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_COPY_DIRECTORY_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot copy file &quot;{0}&quot;:.
        /// </summary>
        internal static string LOC_ERROR_COPY_FILE {
            get {
                return ResourceManager.GetString("LOC_ERROR_COPY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot copy file &quot;{0}&quot;: Access denied. Please, check that you have Write permission for the current directory and file..
        /// </summary>
        internal static string LOC_ERROR_COPY_FILE_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_COPY_FILE_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot create directory: .
        /// </summary>
        internal static string LOC_ERROR_CREATE_DIRECTORY {
            get {
                return ResourceManager.GetString("LOC_ERROR_CREATE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot create directory: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_CREATE_DIRECTORY_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_CREATE_DIRECTORY_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot create thumbnails..
        /// </summary>
        internal static string LOC_ERROR_CREATE_THUMBNAIL {
            get {
                return ResourceManager.GetString("LOC_ERROR_CREATE_THUMBNAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot create thumbnails: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_CREATE_THUMBNAIL_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_CREATE_THUMBNAIL_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot delete directory &quot;{0}&quot;: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_DELETE_DIRECTORY_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_DELETE_DIRECTORY_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot delete directory &quot;{0}&quot;.
        /// </summary>
        internal static string LOC_ERROR_DELETE_DIRECTORY_FILE {
            get {
                return ResourceManager.GetString("LOC_ERROR_DELETE_DIRECTORY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot delete file &quot;{0}&quot;:.
        /// </summary>
        internal static string LOC_ERROR_DELETE_FILE {
            get {
                return ResourceManager.GetString("LOC_ERROR_DELETE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot delete file &quot;{0}&quot;: Access denied. Please, check that you have Write permission for the current directory and file..
        /// </summary>
        internal static string LOC_ERROR_DELETE_FILE_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_DELETE_FILE_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this type of files is not served. Please, change extension of the file to one of supported ones..
        /// </summary>
        internal static string LOC_ERROR_INVALIDEXTENSION {
            get {
                return ResourceManager.GetString("LOC_ERROR_INVALIDEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot move directory &quot;{0}&quot;:.
        /// </summary>
        internal static string LOC_ERROR_MOVE_DIRECTORY {
            get {
                return ResourceManager.GetString("LOC_ERROR_MOVE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot move directory &quot;{0}&quot;: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_MOVE_DIRECTORY_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_MOVE_DIRECTORY_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot move file &quot;{0}&quot;:.
        /// </summary>
        internal static string LOC_ERROR_MOVE_FILE {
            get {
                return ResourceManager.GetString("LOC_ERROR_MOVE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot move file &quot;{0}&quot;: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_MOVE_FILE_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_MOVE_FILE_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download this folder, because neither this folder nor its subfolders have any files..
        /// </summary>
        internal static string LOC_ERROR_NOFILESTOCOMPRESS {
            get {
                return ResourceManager.GetString("LOC_ERROR_NOFILESTOCOMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid name.
        /// </summary>
        internal static string LOC_ERROR_NOTVALIDNAME {
            get {
                return ResourceManager.GetString("LOC_ERROR_NOTVALIDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the working (upload) directory is not specified. Please, specify it with using the fpUploadDir property..
        /// </summary>
        internal static string LOC_ERROR_NOUPLOADDIRECTORY {
            get {
                return ResourceManager.GetString("LOC_ERROR_NOUPLOADDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot rename directory:.
        /// </summary>
        internal static string LOC_ERROR_RENAME_DIRECTORY {
            get {
                return ResourceManager.GetString("LOC_ERROR_RENAME_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot rename directory: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_RENAME_DIRECTORY_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_RENAME_DIRECTORY_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot rename file:.
        /// </summary>
        internal static string LOC_ERROR_RENAME_FILE {
            get {
                return ResourceManager.GetString("LOC_ERROR_RENAME_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot rename file: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_RENAME_FILE_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_RENAME_FILE_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the web session expired or has not been established. Try to refresh the page in the main window and click the Browse button again. If it doesn&apos;t work, contact the support service..
        /// </summary>
        internal static string LOC_ERROR_SESSIONEMPTY {
            get {
                return ResourceManager.GetString("LOC_ERROR_SESSIONEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the file cannot be uploaded: it&apos;s too large. Max file size permitted is {0}..
        /// </summary>
        internal static string LOC_ERROR_TOOLARGEFILE {
            get {
                return ResourceManager.GetString("LOC_ERROR_TOOLARGEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occured while uploading a file:.
        /// </summary>
        internal static string LOC_ERROR_UPLOAD {
            get {
                return ResourceManager.GetString("LOC_ERROR_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occured while uploading a file: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_UPLOAD_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_UPLOAD_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, could not save the file because the file {0} already exist. Hint: check &quot;Rewrite         ///
        ///file if already exists&quot; to enable overwritting files which exist on upload. .
        /// </summary>
        internal static string LOC_ERROR_UPLOAD_FILEEXISTS {
            get {
                return ResourceManager.GetString("LOC_ERROR_UPLOAD_FILEEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot create directory: Access denied..
        /// </summary>
        internal static string LOC_ERROR_ZIP_CANNOTCREATE {
            get {
                return ResourceManager.GetString("LOC_ERROR_ZIP_CANNOTCREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot create Zip file: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_ZIP_CANNOTCREATE_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_ZIP_CANNOTCREATE_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download this folder: cannot create a zip archive if the name of the folder contains non-English letters..
        /// </summary>
        internal static string LOC_ERROR_ZIP_CANNOTCREATE_WRONGNAME {
            get {
                return ResourceManager.GetString("LOC_ERROR_ZIP_CANNOTCREATE_WRONGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot extract Zip file:.
        /// </summary>
        internal static string LOC_ERROR_ZIP_CANNOTEXTRACT {
            get {
                return ResourceManager.GetString("LOC_ERROR_ZIP_CANNOTEXTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, cannot extract Zip file: Access denied. Please, check that you have Write permission for the current directory..
        /// </summary>
        internal static string LOC_ERROR_ZIP_CANNOTEXTRACT_ACCESSDENIED {
            get {
                return ResourceManager.GetString("LOC_ERROR_ZIP_CANNOTEXTRACT_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 archive created ({0}) with {1} file(s).
        /// </summary>
        internal static string LOC_LABEL_1ARCHIVECREATED {
            get {
                return ResourceManager.GetString("LOC_LABEL_1ARCHIVECREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 directory renamed.
        /// </summary>
        internal static string LOC_LABEL_1DIRECTORYRENAMED {
            get {
                return ResourceManager.GetString("LOC_LABEL_1DIRECTORYRENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 file renamed.
        /// </summary>
        internal static string LOC_LABEL_1FILERENAMED {
            get {
                return ResourceManager.GetString("LOC_LABEL_1FILERENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 file uploaded.
        /// </summary>
        internal static string LOC_LABEL_1FILEUPLOADED {
            get {
                return ResourceManager.GetString("LOC_LABEL_1FILEUPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 file uploaded with {0} files.
        /// </summary>
        internal static string LOC_LABEL_1FILEUPLOADEDWITHFILES {
            get {
                return ResourceManager.GetString("LOC_LABEL_1FILEUPLOADEDWITHFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 new folder created.
        /// </summary>
        internal static string LOC_LABEL_1NEWFOLDERCREATED {
            get {
                return ResourceManager.GetString("LOC_LABEL_1NEWFOLDERCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string LOC_LABEL_ACTION {
            get {
                return ResourceManager.GetString("LOC_LABEL_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string LOC_LABEL_BOTTOM {
            get {
                return ResourceManager.GetString("LOC_LABEL_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came into Recycle Bin.
        /// </summary>
        internal static string LOC_LABEL_CAMEINTORECYCLEBIN {
            get {
                return ResourceManager.GetString("LOC_LABEL_CAMEINTORECYCLEBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed?.
        /// </summary>
        internal static string LOC_LABEL_DELETECONFIRM {
            get {
                return ResourceManager.GetString("LOC_LABEL_DELETECONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir.
        /// </summary>
        internal static string LOC_LABEL_DIR {
            get {
                return ResourceManager.GetString("LOC_LABEL_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir(s):.
        /// </summary>
        internal static string LOC_LABEL_DIRS {
            get {
                return ResourceManager.GetString("LOC_LABEL_DIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept or decline name change before doing anything with a file or folder..
        /// </summary>
        internal static string LOC_LABEL_EDITMODEWARNING {
            get {
                return ResourceManager.GetString("LOC_LABEL_EDITMODEWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LOC_LABEL_ERROR {
            get {
                return ResourceManager.GetString("LOC_LABEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_CANCEL {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LOC_LABEL_FILELIST_CHECK {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_DOWNLOAD {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_DOWNLOADFILE {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_DOWNLOADFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the entire folder in zip archive.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_DOWNLOADFOLDER {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_DOWNLOADFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_LENGTH {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_NAME {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_RENAME {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Unselect All.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_SELECTALL {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_SELECTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_UPDATE {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string LOC_LABEL_FILELIST_UPDATED {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILELIST_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s).
        /// </summary>
        internal static string LOC_LABEL_FILES {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) checked.
        /// </summary>
        internal static string LOC_LABEL_FILESCHECKED {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILESCHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) copied.
        /// </summary>
        internal static string LOC_LABEL_FILESCOPIED {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILESCOPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) cut.
        /// </summary>
        internal static string LOC_LABEL_FILESCUT {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILESCUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) deleted.
        /// </summary>
        internal static string LOC_LABEL_FILESDELETED {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILESDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) found.
        /// </summary>
        internal static string LOC_LABEL_FILESFOUND {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILESFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) pasted.
        /// </summary>
        internal static string LOC_LABEL_FILESPASTED {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILESPASTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) restored.
        /// </summary>
        internal static string LOC_LABEL_FILESRESTORED {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILESRESTORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files unzipped with {1} files.
        /// </summary>
        internal static string LOC_LABEL_FILESUNZIPPED {
            get {
                return ResourceManager.GetString("LOC_LABEL_FILESUNZIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string LOC_LABEL_GO {
            get {
                return ResourceManager.GetString("LOC_LABEL_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info:.
        /// </summary>
        internal static string LOC_LABEL_INFO {
            get {
                return ResourceManager.GetString("LOC_LABEL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string LOC_LABEL_KB {
            get {
                return ResourceManager.GetString("LOC_LABEL_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launched....
        /// </summary>
        internal static string LOC_LABEL_LAUNCHED {
            get {
                return ResourceManager.GetString("LOC_LABEL_LAUNCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a list of masks separated by semicolon to check..
        /// </summary>
        internal static string LOC_LABEL_MASKSCHECK {
            get {
                return ResourceManager.GetString("LOC_LABEL_MASKSCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a list of masks separated by semicolon for search..
        /// </summary>
        internal static string LOC_LABEL_MASKSSEARCH {
            get {
                return ResourceManager.GetString("LOC_LABEL_MASKSSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved one folder down.
        /// </summary>
        internal static string LOC_LABEL_MOVEDONEFOLDERDOWN {
            get {
                return ResourceManager.GetString("LOC_LABEL_MOVEDONEFOLDERDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved one folder up.
        /// </summary>
        internal static string LOC_LABEL_MOVEDONEFOLDERUP {
            get {
                return ResourceManager.GetString("LOC_LABEL_MOVEDONEFOLDERUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved to root.
        /// </summary>
        internal static string LOC_LABEL_MOVEDTOROOT {
            get {
                return ResourceManager.GetString("LOC_LABEL_MOVEDTOROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string LOC_LABEL_NEWFOLDER {
            get {
                return ResourceManager.GetString("LOC_LABEL_NEWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string LOC_LABEL_PATH {
            get {
                return ResourceManager.GetString("LOC_LABEL_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string LOC_LABEL_PLEASEWAIT {
            get {
                return ResourceManager.GetString("LOC_LABEL_PLEASEWAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        internal static string LOC_LABEL_RECYCLEBIN {
            get {
                return ResourceManager.GetString("LOC_LABEL_RECYCLEBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LOC_LABEL_RECYCLEBIN_DELETE {
            get {
                return ResourceManager.GetString("LOC_LABEL_RECYCLEBIN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string LOC_LABEL_RECYCLEBIN_RESTORE {
            get {
                return ResourceManager.GetString("LOC_LABEL_RECYCLEBIN_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen refreshed.
        /// </summary>
        internal static string LOC_LABEL_REFRESHED {
            get {
                return ResourceManager.GetString("LOC_LABEL_REFRESHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string LOC_LABEL_SEARCHTABLE_LENGTH {
            get {
                return ResourceManager.GetString("LOC_LABEL_SEARCHTABLE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LOC_LABEL_SEARCHTABLE_NAME {
            get {
                return ResourceManager.GetString("LOC_LABEL_SEARCHTABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string LOC_LABEL_SEARCHTABLE_PATH {
            get {
                return ResourceManager.GetString("LOC_LABEL_SEARCHTABLE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string LOC_LABEL_SEARCHTABLE_UPDATED {
            get {
                return ResourceManager.GetString("LOC_LABEL_SEARCHTABLE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        internal static string LOC_LABEL_SELECTAFILE {
            get {
                return ResourceManager.GetString("LOC_LABEL_SELECTAFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string LOC_LABEL_TOP {
            get {
                return ResourceManager.GetString("LOC_LABEL_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string LOC_LABEL_TOTAL {
            get {
                return ResourceManager.GetString("LOC_LABEL_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_DONOTHING {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_DONOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a Zip file is uploaded.
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_IFZIPUPLOADED {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_IFZIPUPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_OPTIONS {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite the file if already exists&amp;nbsp;**.
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_OVERWRITE {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file upon upload&amp;nbsp;*.
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_SELECTUPONUPLOAD {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_SELECTUPONUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip &amp; delete Zip file.
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_UNZIPANDDELETE {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_UNZIPANDDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip and retain Zip file.
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_UNZIPANDRETAIN {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_UNZIPANDRETAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_UPLOADFILE {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_UPLOADFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *&amp;nbsp;Applicable for a ZIP archive to be extracted upon upload.&lt;br&gt;
        ///**&amp;nbsp;Files extracted from a ZIP archive will overwrite the existing files anyway. .
        /// </summary>
        internal static string LOC_LABEL_UPLOAD_UPLOADNOTE {
            get {
                return ResourceManager.GetString("LOC_LABEL_UPLOAD_UPLOADNOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Went to found file..
        /// </summary>
        internal static string LOC_LABEL_WENTTOFOUNDFILE {
            get {
                return ResourceManager.GetString("LOC_LABEL_WENTTOFOUNDFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Zip file called as the first file checked.
        /// </summary>
        internal static string LOC_LABEL_ZIP_CREATEZIP {
            get {
                return ResourceManager.GetString("LOC_LABEL_ZIP_CREATEZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnZip here.
        /// </summary>
        internal static string LOC_LABEL_ZIP_UNZIPHERE {
            get {
                return ResourceManager.GetString("LOC_LABEL_ZIP_UNZIPHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnZip checked ZIP files into a new directory.
        /// </summary>
        internal static string LOC_LABEL_ZIP_UNZIPINTODIRECTORY {
            get {
                return ResourceManager.GetString("LOC_LABEL_ZIP_UNZIPINTODIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip checked files &amp;amp; download.
        /// </summary>
        internal static string LOC_LABEL_ZIP_ZIPANDDOWNLOAD {
            get {
                return ResourceManager.GetString("LOC_LABEL_ZIP_ZIPANDDOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Recycle Bin.
        /// </summary>
        internal static string LOC_LEFTRECYCLEBIN {
            get {
                return ResourceManager.GetString("LOC_LEFTRECYCLEBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string LOC_PREFIX_THECOPY {
            get {
                return ResourceManager.GetString("LOC_PREFIX_THECOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string LOC_TOOLBAR_COPY {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string LOC_TOOLBAR_CUT {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LOC_TOOLBAR_DELETE {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with Zip archives.
        /// </summary>
        internal static string LOC_TOOLBAR_DOWNLOADANDZIP {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_DOWNLOADANDZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Check.
        /// </summary>
        internal static string LOC_TOOLBAR_MASKCHECK {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_MASKCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string LOC_TOOLBAR_NEWFOLDER {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_NEWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string LOC_TOOLBAR_PASTE {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        internal static string LOC_TOOLBAR_RECYCLEBIN {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_RECYCLEBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string LOC_TOOLBAR_REFRESH {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Check.
        /// </summary>
        internal static string LOC_TOOLBAR_REVERSECHECK {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_REVERSECHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string LOC_TOOLBAR_ROOT {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LOC_TOOLBAR_SEARCH {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Thumbnails.
        /// </summary>
        internal static string LOC_TOOLBAR_SEETHUMBNAILS {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_SEETHUMBNAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string LOC_TOOLBAR_UP {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string LOC_TOOLBAR_UPLOAD {
            get {
                return ResourceManager.GetString("LOC_TOOLBAR_UPLOAD", resourceCulture);
            }
        }
    }
}
